### ISSUE TITLE
StateChanged bug

### ISSUE THREAD

**Issue by bbhxwl** [winnster/DotRas#101]
I use WinForm net framework4

install DotRas.for.Win8   
My computer is win10

I connected successfully, but the status couldn't be captured.

The latest version of 2.0 does not support net framework 4, because many computers exist in this version, and it is not necessary to re install the running environment.

`
 public static void CreateOrUpdate(string connectionName,string serverAddress, RasVpnStrategy rasVpn) {
          
            var name = "";
            if (rasVpn== RasVpnStrategy.SstpFirst)
            {
                name = "SSTP";
            }
            else if (rasVpn == RasVpnStrategy.PptpFirst)
            {
                name = "PPTP";
            }
            else if (rasVpn == RasVpnStrategy.L2tpFirst)
            {
                name = "L2TP";

            }
           
            var rasDevice = RasDevice.GetDevices().FirstOrDefault(c => c.Name.Contains(name));
            if (rasDevice == null)
            {
                throw new Exception("No device found.");
            }
            if (VPNHelper.dialer==null)
            {
                VPNHelper.dialer = new RasDialer();
                 
                VPNHelper.dialer.StateChanged += Dialer_StateChanged;
                VPNHelper.dialer.DialCompleted += Dialer_DialCompleted;
            }
            //dialer.StateChanged += Dialer_StateChanged;
            using (var allUsersPhoneBook = new RasPhoneBook())
            {
                allUsersPhoneBook.Open(true);
                 
                if (allUsersPhoneBook.Entries.Contains(connectionName))
                {
                    allUsersPhoneBook.Entries[connectionName].PhoneNumber = serverAddress;
                    allUsersPhoneBook.Entries[connectionName].VpnStrategy = rasVpn;
                    allUsersPhoneBook.Entries[connectionName].Device = rasDevice;
                    allUsersPhoneBook.Entries[connectionName].Update();
                   
                }
                else
                {
                    RasEntry entry = RasEntry.CreateVpnEntry(connectionName, serverAddress, rasVpn, rasDevice);
                    allUsersPhoneBook.Entries.Add(entry);
                    dialer.EntryName = connectionName;
                    dialer.PhoneBookPath = RasPhoneBook.GetPhoneBookPath(RasPhoneBookType.AllUsers);

                }
             }
           
 

        }

`

`
 private static void Dialer_DialCompleted(object sender, DialCompletedEventArgs e)
        {
 
            Console.WriteLine("ok");
        }

        public static void Connect(string uid,string pwd) {

            dialer.Credentials = new NetworkCredential(uid, pwd);
            dialer.Dial();
        }
        private static void Dialer_StateChanged(object sender, StateChangedEventArgs e)
        {
             Console.WriteLine(e.State.ToString());
         }
`

**Comment by jeff-winn** [comment]
Unfortunately as mentioned to others, the legacy API is no longer being supported.
