### ISSUE TITLE
Certificate not valid issue

### ISSUE THREAD

**Issue by NikasZalias** [winnster/DotRas#73]
I'm not sure if this is your scope problem or is it window's, but maybe you can answer me.

So user has to install a certificate in order to connect to some server. Let's say server host is myhost.com and it's IP is 111.111.111.111. The certificate is made to be valid for host myhost.com and when connecting to myhost.com everything works, but when connecting to host's IP 111.111.111.111 DotRas throws an error that certificate is invalid.

 Is it DotRas scope issue or it's more low-level issue? Cause there is no such problem on Apple or Android.

**Comment by jeff-winn** [comment]
Generally speaking certificates are validated against the common name (myhost.com) and where you connect must match exactly.

I don’t have anything in place to explicitly handle the certificate validation, so it’s probably just using the “normal” behavior.

**Comment by jeff-winn** [comment]
I glanced around the RasDial API and couldn't find anything explicitly that would allow you to control the certificate validation response.

When the exception occurs, what's the RasConnectionState of the RasDialer component?

**Comment by NikasZalias** [comment]
I'm getting exception just after I get `IAuthNotify` state two times (should I get it two times?).
Exception: `RasException (ErrorCode = 13801) DotRas.RasDialException: Exception of type 'DotRas.RasDialException' was thrown.`
And that's it...

**Comment by jeff-winn** [comment]
It probably occurs twice because the first one has a 0 error code (in which it's letting you attempt to validate the certificate) and the second attempt it's a non-zero error which throws the exception you're seeing.

Does the rasdial.exe and rasphone.exe behave the same way when dialing the connection? You won't see the state changes, but they should error out the same as DotRas does.

PS: I didn't see anything in the Windows SDK related to that state allowing a callback function either.

**Comment by jeff-winn** [comment]
Are you using the 1.X version of the product or the 2.X version that is hosted here? There is no RasDialException currently in the codebase and the 1.X version is archived in another repository.

**Comment by NikasZalias** [comment]
I'm using the 1.3.0 version. Thanks for the answers! Realy waiting for 2.0 version :)

**Comment by jeff-winn** [comment]
Does 2.0 have the same issue? It's listed on NuGet as a preview right now (there is not feature parity currently as the surface area to try and rewrite is too large for one giant release).

**Comment by NikasZalias** [comment]
Haven't tried it yet

**Comment by jeff-winn** [comment]
Would you mind trying it out? I'd love some feedback from others actually using it since it's a ground up rewrite.

**Comment by jeff-winn** [comment]
Found this in the Windows SDK, 13801 is defined in the winerror.h file as:
ERROR_IPSEC_IKE_AUTH_FAIL

I wonder if I need an IpSecException added. Not sure if they have a string lookup anywhere for a friendly name.
