### ISSUE TITLE
Trying to connect to existing entry throws error.

### ISSUE THREAD

**Issue by NikasZalias** [winnster/DotRas#95]
Hello, I haven't noticed yet which windows update made DotRas behave like this, but now I'm getting this error when trying to connect with the existing entry.

```
DotRas.RasDialException: The remote connection was denied because the user name and password combination you provided is not recognized, or the selected authentication protocol is not permitted on the remote access server.
ErrorCode = 691
```

I tried to update username and password but I still need to delete the existing entry and recreate a new one...

Currently using DotRas 1.3.0. Is there a workaround for this issue? Will this problem will be fixed in the 2.0.0 version?

**Comment by jeff-winn** [comment]
1.X is no longer supported, as for whether this code base exhibits the behavior the only way to know is to try it. It does throw an error if the credentials are wrong, you would just need to use the correct credentials.

This is a rewrite, aside from the Win32 API signatures and what the public classes mostly look like not much has been kept.
