### ISSUE TITLE
RasEntry should be able to ignore DNS servers from VPN server if I don't want them.

### ISSUE THREAD

**Issue by NikasZalias** [winnster/DotRas#96]
Would it be possible to make RasEntry to have a parameter where I can make it ignore DNS servers that are gotten from VPN server? Cause if I set desired DNS servers like that:
` entry.DnsAddress = "1.1.1.1";
  entry.DnsAddressAlt = "8.8.8.8";`

I still get another DNS servers on my IKEv2 interface.

**Comment by jeff-winn** [comment]
As far as DotRas v2 I plan on keeping much of that sort of validation logic out of the code.

Reason being, if Windows lets you the code should behave the same and not put unnecessary restrictions on it.

**Comment by jmithy** [comment]
Hello @NikasZalias.  I'm curious to know if you were able to disregard the DNS settings provided by the VPN. I have a similar need, but I haven't been able to find a solution so far. Your assistance would be greatly valued.
