### ISSUE TITLE
Creating new entry - creates new registry entry

### ISSUE THREAD

**Issue by NikasZalias** [winnster/DotRas#98]
Hey,

while using DotRas 1.3 I noticed that every time I create a new entry - a new registry entry creates AND when deleting existing entry - it doesn't delete registry entry. In that case - a lot of useless registry entries remain. Will this be fixed in 2.0?

**Comment by jeff-winn** [comment]
As far as I can recall, there wasn't anything specifically in DotRas 1.x that created registry entries, if Microsoft does something within their API I'm not entirely sure.

As for DotRas 2.x, I have no plans to do anything with the registry at this time.
